import { Caesar_Dressing, Raleway } from 'next/font/google'
import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./client-layout";

const caesarDressing = Caesar_Dressing({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-caesar-dressing'
})

const raleway = Raleway({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-raleway'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${caesarDressing.variable} ${raleway.variable} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
